name = "PTYQoL"
uuid = "551ad714-b11a-4605-8871-12721def4e72"
authors = ["Tianyi Pu <912396513@qq.com> and contributors"]
version = "0.2.1"

[weakdeps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
CircularArrays = "7a955b69-7140-5f4e-a0ed-f168c5e2e749"
ContinuumArrays = "7ae1f121-cc2c-504b-ac30-9b923412ae5c"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
QuasiArrays = "c4ea9172-b204-11e9-377d-29865faadc5c"
ClassicalOrthogonalPolynomials = "b30e2e7b-c4ee-47da-9d5f-2c5c27239acd"
InfiniteArrays = "4858937d-0d70-526a-a4dd-2d5cb5dd786c"
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
ArrayLayouts = "4c555306-a7a7-4459-81d9-ec55ddd5c99a"
AlgebraicNumbers = "e86d093a-a386-599e-b7c7-df0420c8bcba"

[extensions]
PTYQoLLinearAlgebraExt = "LinearAlgebra"
PTYQoLCircularArraysExt = "CircularArrays"
PTYQoLContinuumArraysExt = "ContinuumArrays"
PTYQoLIntervalSetsExt = "IntervalSets"
PTYQoLQuasiArraysExt = "QuasiArrays"
PTYQoLClassicalOrthogonalPolynomialsExt = "ClassicalOrthogonalPolynomials"
PTYQoLInfiniteArraysExt = "InfiniteArrays"
PTYQoLBandedMatricesExt = "BandedMatrices"
PTYQoLArrayLayoutsExt = "ArrayLayouts"
PTYQoLAlgebraicNumbersExt = "AlgebraicNumbers"

[compat]
julia = "1"

[extras]
ContinuumArrays = "7ae1f121-cc2c-504b-ac30-9b923412ae5c"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DomainSets = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ClassicalOrthogonalPolynomials = "b30e2e7b-c4ee-47da-9d5f-2c5c27239acd"
InfiniteArrays = "4858937d-0d70-526a-a4dd-2d5cb5dd786c"
ArrayLayouts = "4c555306-a7a7-4459-81d9-ec55ddd5c99a"
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
AlgebraicNumbers = "e86d093a-a386-599e-b7c7-df0420c8bcba"

[targets]
test = ["Test", "Aqua", "LinearAlgebra", "Documenter", "DomainSets", "ContinuumArrays", "ClassicalOrthogonalPolynomials", "InfiniteArrays", "ArrayLayouts", "AlgebraicNumbers"]
