name = "PTYQoL"
uuid = "551ad714-b11a-4605-8871-12721def4e72"
authors = ["Tianyi Pu <912396513@qq.com> and contributors"]
version = "0.1.0"

[weakdeps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ApproxFunBase = "fbd15aa5-315a-5a7d-a8a4-24992e37be05"

[extensions]
PTYQoLLinearAlgebraExt = "LinearAlgebra"
PTYQoLApproxFunBaseExt = "ApproxFunBase"

[compat]
julia = "1"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "LinearAlgebra"]
